apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "microinsight.fullname" . }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "microinsight.name" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "microinsight.name" . }}"
    spec:
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecrets }}"
      containers:
        - name: microinsight
          image: {{ if eq .Values.image.tag "latest" }}{{ .Values.image.tag }}{{ else }}v{{ .Values.image.tag }}{{ end }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_NAME
            - name: INTERVAL
              value: "{{ .Values.interval }}"
            - name: LOG_LEVEL
              value: "{{ .Values.loglevel }}"
            - name: THREADS
              value: "{{ .Values.threads }}"
