apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # prettier-ignore
  DB_HOST: {{ .Values.db.host | b64enc | quote }}
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASS: {{ .Values.db.pass | b64enc | quote }}
  DB_NAME: {{ .Values.db.name | b64enc | quote }}
